### ISSUE TITLE
Some tests are not displayed

### ISSUE THREAD

**Issue by friendnick** [matepek/vscode-catch2-test-adapter#103]
When I refresh the tests toolbar, it doesn't show all tests I have in the specified folder.

My settings are:
```json
"catch2TestExplorer.executables": [
    {
        "name": "${filename}",
        "pattern": "/absoluteTestFolderPath/*{test,Test,TEST}*"
    }
]
```

The logpanel output for the not found tests is the following:
```
[2019-06-26 18:47:42.655] [WARN] [at load.suiteCreationAndLoadingTasks.push.c2fs.isNativeExecutableAsync.then._createSuiteByUri.then (/home/user/.vscode/extensions/matepek.vscode-catch2-test-adapter-2.5.0/out/src/TestExecutableInfo.js:73:38)] Not a test executable: /absoluteTestFolderPath/HistogramTest reason: [Error: FsWrapper.spawnAsync signal: SIGABRT
	at ChildProcess.<anonymous> (/home/user/.vscode/extensions/matepek.vscode-catch2-test-adapter-2.5.0/out/src/FSWrapper.js:36:24)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:961:16)
	at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:380:11)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)]
```

**Comment by matepek** [comment]
Can you run your test executable manually with `--help`?

**Comment by friendnick** [comment]
Yes

**Comment by matepek** [comment]
How long does it take to produce that? If shorter than 5 sec I have no idea. Can you send me the exec? What kind of os. ...

**Comment by matepek** [comment]
Let me know if you still have the issue

**Comment by friendnick** [comment]
The issue still remains. The exec is super fast, I can send it to you

**Comment by matepek** [comment]
It is welcomed

**Comment by friendnick** [comment]
[ImageWriterTest.zip](https://github.com/matepek/vscode-catch2-test-adapter/files/3411356/ImageWriterTest.zip)

**Comment by matepek** [comment]
linux?

**Comment by friendnick** [comment]
yes

**Comment by friendnick** [comment]
I finally find why this was happening. The code outside of google testing was sending the exception and crashed the executable, so the catch2 script thought it wasn't an executable.
Could the extension handle that and still show that this test executable has crashed?

**Comment by friendnick** [comment]
Also the exception was sent because of not getting the environment variables that cannot be set with "env", could this also be implemented? See details: #116

**Comment by matepek** [comment]
Sorry, but my linux VM is deep inside cupboard. :)

Check my comment on the issue you mentioned.

Let me know if you have any questions.

**Comment by friendnick** [comment]
I think I mixed too many things here, will create a new, more clear version)
