### ISSUE TITLE
Nested SECTION crashes

### ISSUE THREAD

**Issue by scrcro** [matepek/vscode-catch2-test-adapter#153]
**The extension crashes if I have nested SECTIONS** 
**Steps to reproduce the behavior** 

1. Have a nested SECTION
2. Execute the test

**Screenshots** (If applicable, add screenshots to help explain your problem.)

- Extension Version 2.8.1

**Comment by matepek** [comment]
It works for me. I encourage you to describe your case properly, because I need more info if I want to reproduce.

**Comment by scrcro** [comment]
Here is what I see:
 Unexpected error under parsing output !! Error: [Error: [Error: Invalid character in tag name
Line: 15
Column: 128
Char: <
	at N (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:23:6380)
	at A (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:23:6756)
	at i.write (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:84870)
	at i.parseString (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:78554)
	at i.parseString (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:73134)
	at c.parseAndProcessTestCase (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:16:105066)
	at s (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:52861)
	at Socket.<anonymous> (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:54354)
	at Socket.emit (events.js:200:13)
	at Socket.EventEmitter.emit (domain.js:471:20)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)]
	at /xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:16:105099
	at i.<anonymous> (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:78373)
	at i.emit (events.js:200:13)
	at i.EventEmitter.emit (domain.js:471:20)
	at i.saxParser.onerror (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:75197)
	at O (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:23:6044)
	at N (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:23:6403)
	at A (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:23:6756)
	at i.write (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:84870)
	at i.parseString (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:78554)
	at i.parseString (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:73134)
	at c.parseAndProcessTestCase (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:16:105066)
	at s (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:52861)
	at Socket.<anonymous> (/xxxx/xxxx/.vscode-server-insiders/extensions/matepek.vscode-catch2-test-adapter-2.8.2/out/dist/main.js:22:54354)
	at Socket.emit (events.js:200:13)
	at Socket.EventEmitter.emit (domain.js:471:20)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)]

The test looks like this:
`SECTION("Tests for HSM")
{
    // If everything works without any failure we have crossed the first step.
    --Code here --
    SECTION("Test Forward Output")
    {
    }
    SECTION("Another Test")
    {
    }
}`

**Comment by matepek** [comment]
Please share an executable with which I can reproduce the issue locally
