### ISSUE TITLE
Not a supported test executable (Catch2 on remote ssh)

### ISSUE THREAD

**Issue by gatopeich** [matepek/vscode-catch2-test-adapter#201]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.

**Describe the bug**
I have a simple Catch2 test suite that runs fine from command line and vscode tasks.
However its test cases don't get listed in Test Explorer.
Here is a sample run of it with "-l":
```
{workspace-root} $ build/Tests -l
All available test cases:
  Load library and register callbacks
      [init]
1 test case
```

**Desktop**

- Extension Version: latest
- VS Code Version: latest
- Catch2 / Google Test / DOCTest Version: Catch2 v2.12.1
- OS Type and Version: Ubuntu 18 LTS
- Using remote-ssh/docker/wsl?: Yes, remote-ssh

**Log** (optional but recommended)

```
[2020-05-15 12:48:20.146] [DEBUG] Not a test executable: /home/$USER/{workspace-root}/build/Tests reason: [Error: Not a supported test executable: /home/$USER/{workspace-root}/build/Tests
 output: 
        at /home/$USER/.vscode-server/extensions/matepek.vscode-catch2-test-adapter-3.2.0/out/dist/main.js:23:34044
        at async e.ExecutableConfig.load (/home/$USER/.vscode-server/extensions/matepek.vscode-catch2-test-adapter-3.2.0/out/dist/main.js:23:27220)
        at async Promise.all (index 0)
        at async o.load (/home/$USER/.vscode-server/extensions/matepek.vscode-catch2-test-adapter-3.2.0/out/dist/main.js:22:29374)]
[2020-05-15 12:48:20.146] [INFO] load finished 0
```

**Comment by matepek** [comment]
Please attaché the output for ‘—help’

**Comment by gatopeich** [comment]
[Tests --help.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/4634920/Tests.--help.txt)

**Comment by gatopeich** [comment]
```
$ build/Tests "[.],*" --verbosity high --list-tests --use-colour no
Matching test cases:
  Load library and register callbacks
    Tests.cpp:17
    (NO DESCRIPTION)
      [init]
1 matching test case
```

**Comment by matepek** [comment]
Oh man that's tricky.
I have a similar issue with docker. I'm almost sure that it is not related to this extension but the vscode or vscode-remote.

What we can do that if you could send me over the file I can try it on my Ubuntu VM.
Or the best would be if I could remote SSH to your computer. (if the first doesn't work we still can try this). I have a vpn server if you don have public IP.

**Comment by gatopeich** [comment]
I am seeing the same in non-remote work.

Attaching a simple test built on Ubuntu 18:
[DumbTests.gz](https://github.com/matepek/vscode-catch2-test-adapter/files/4635730/DumbTests.gz) (run gunzip on it first!)

from this code:
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE("Catch2 works", "[init]")
{
    REQUIRE(true);
}
```

**Comment by matepek** [comment]
Hm... try to add execution flag. `chmod +x Tests`.
Is it help?

**Comment by gatopeich** [comment]
Okay I found the issue: there was a dynamic linked library with a relative path.
It could only run from the workspace root dir.

**Comment by matepek** [comment]
You can change the `cwd`. That would solve your problem with the extension.

**Comment by gatopeich** [comment]
Thanks and sorry, it works fine on non-remote with the `cwd`, BUT it still fails remotely :-(

**Comment by gatopeich** [comment]
It may have something to do with this log I found in the Remote Extension log:
```
[2020-05-15 18:29:02.569] [exthost] [error] /home/apozuelo/.vscode-server/extensions/matepek.vscode-catch2-test-adapter-3.2.0/out/dist/main.js:3829
 return r || (r = s), h += t.slice(u, c).replace(lt, Me), n && (i = !0, h += "' +\n__e(" + n + ") +\n'"), a && (o = !0, h += "';\n" + a + ";\n__p += '"), r && (h += "' +\n((__t = (" + r + ")) == null ? '' : __t) +\n'"), u = c + e.length, e })), h += "';\n"; var d = Tt.call(e, "variable") && e.variable; d || (h = "with (obj) {\n" + h + "\n}\n"), h = (o ? h.replace(I, "") : h).replace(D, "$1").replace(j, "$1;"), h = "function(" + (d || "obj") + ") {\n" + (d ? "" : "obj || (obj = {});\n") + "var __t, __p = ''" + (i ? ", __e = _.escape" : "") + (o ? ", __j = Array.prototype.join;\nfunction print() {
                                                                                                                                                                                                                                                                                                                           

SyntaxError: Invalid or unexpected token
	at Module._compile (internal/modules/cjs/loader.js:718:23)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
	at Module.load (internal/modules/cjs/loader.js:641:32)
	at Function.Module._load (internal/modules/cjs/loader.js:556:12)
	at Function.t._load (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:976:769)
	at Function.i._load (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:946:106)
	at Function.r._load (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:942:391)
	at Module.require (internal/modules/cjs/loader.js:681:19)
	at require (internal/modules/cjs/helpers.js:16:16)
	at Function.s [as __$__nodeRequire] (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:33:115)
	at h._loadCommonJSModule (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:947:266)
	at h._doActivateExtension (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:843:856)
	at h._activateExtension (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:842:937)
	at Object.actualActivateExtension (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:840:883)
	at e._activateExtension (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:619:859)
	at /home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:619:537
	at Array.map (<anonymous>)
	at e._activateExtensions (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:619:525)
	at e.activateByEvent (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:617:14)
	at h._activateByEvent (/home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:841:618)
	at /home/apozuelo/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:850:401
	at processTicksAndRejections (internal/process/task_queues.js:89:5)```

**Comment by gatopeich** [comment]
Thanks that worked!

**Comment by eliveikis** [comment]
@matepek Before I file a new bug, could this be related to the issue I've been having on Windows VSCode connecting to WSL2 ubuntu 18.04? No tests show in the explorer, nor do the Run|Debug|Etc options show above the individual tests.

Microsoft has this document to reference for extension issues in WSL2:
https://code.visualstudio.com/docs/remote/troubleshooting#_extension-tips

**Comment by matepek** [comment]
Assuming that "this" means this issue(201): yes, this can cause symptoms like that.
