### ISSUE TITLE
Environment variables doesn't works on the lookup step

### ISSUE THREAD

**Issue by maximMalofeev** [matepek/vscode-catch2-test-adapter#272]
**Checklist**

- [ *] The issue is about this extension and NOT about a fork.
- [ *] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [ *] The latest version of the extension was used.
- [ *] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

My test exe, based on gtest, depends on qt binaries that not in the working dir and not in the Path env. That why test explorer cant run my test exe. I try to set "env" property in "testMate.cpp.test.advancedExecutables" as {"PATH": "${os_env:PATH};c:/Path/to/qt/bin"}, but it is doesn't work. It looks like the env changes only on the run step, bun not on the lookup step. The only way at the moment to discover my tests is set "cwd" property to the qt dir.

**To Reproduce**

1: Link some test exe with external binaries
2: Try to find tests

**Screenshots** (optional)

**Desktop**

- Extension Version: 3.6.27
- VS Code Version: 1.59
- Catch2 / Google Test / DOCTest Version: 
- OS Type and Version: Windows 10
- Using remote-ssh/docker/wsl?: no

**Regression bug?**

- Last extension version in which the feature were working:

**Log** (optional but recommended)

[2021-08-16 08:46:22.134] [INFO] load called
[2021-08-16 08:46:22.134] [DEBUG] canceled
[2021-08-16 08:46:22.134] [INFO] context:executables [
  {
    pattern: 'C:/Users/maxim/develop/nx-build/Debug/bin/nx_vms_client_desktop_ut.exe',
    gtest: { ignoreTestEnumerationStdErr: true }
  }
]
[2021-08-16 08:46:22.134] [INFO] load started
[2021-08-16 08:46:22.135] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: 'C:/Users/maxim/develop/nx-build/Debug/bin/nx_vms_client_desktop_ut.exe',
  resolved: 'C:/Users/maxim/develop/nx-build/Debug/bin/nx_vms_client_desktop_ut.exe',
  strictAllowed: false
}
[2021-08-16 08:46:22.135] [INFO] pattern C:/Users/maxim/develop/nx-build/Debug/bin/nx_vms_client_desktop_ut.exe c:\Users\maxim\develop\nx {
  isAbsolute: true,
  absPath: 'c:\\Users\\maxim\\develop\\nx-build\\Debug\\bin\\nx_vms_client_desktop_ut.exe',
  isPartOfWs: false,
  relativeToWsPosix: '../nx-build/Debug/bin/nx_vms_client_desktop_ut.exe'
}
[2021-08-16 08:46:22.258] [DEBUG] Checking file for tests: c:\Users\maxim\develop\nx-build\Debug\bin\nx_vms_client_desktop_ut.exe
[2021-08-16 08:46:22.258] [DEBUG] Checking file for tests: c:\Users\maxim\develop\nx-build\Debug\bin\fonts\
[2021-08-16 08:46:22.258] [DEBUG] Checking file for tests: c:\Users\maxim\develop\nx-build\Debug\bin\help\
[2021-08-16 08:46:22.258] [DEBUG] Checking file for tests: c:\Users\maxim\develop\nx-build\Debug\bin\plugins\
[2021-08-16 08:46:22.258] [DEBUG] Checking file for tests: c:\Users\maxim\develop\nx-build\Debug\bin\plugins_optional\
[2021-08-16 08:46:22.258] [DEBUG] Checking file for tests: c:\Users\maxim\develop\nx-build\Debug\bin\translations\
[2021-08-16 08:46:22.258] [DEBUG] Checking file for tests: c:\Users\maxim\develop\nx-build\Debug\bin\vmaxproxy\
[2021-08-16 08:46:22.258] [DEBUG] Not an executable: c:\Users\maxim\develop\nx-build\Debug\bin\fonts\ [Error: Not a native executable extension on win32: c:\Users\maxim\develop\nx-build\Debug\bin\fonts\
	at Object.e.isNativeExecutableAsync (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:437987)
	at c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:337692
	at e.ExecutableConfig.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:338544)
	at async Promise.all (index 0)
	at async o.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:346914)
	at async e.SharedVariables._shared.u.SharedVariables.e [as loadWithTask] (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:368776)
	at async m.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:373851)]
[2021-08-16 08:46:22.259] [DEBUG] Not an executable: c:\Users\maxim\develop\nx-build\Debug\bin\help\ [Error: Not a native executable extension on win32: c:\Users\maxim\develop\nx-build\Debug\bin\help\
	at Object.e.isNativeExecutableAsync (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:437987)
	at c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:337692
	at e.ExecutableConfig.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:338544)
	at async Promise.all (index 0)
	at async o.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:346914)
	at async e.SharedVariables._shared.u.SharedVariables.e [as loadWithTask] (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:368776)
	at async m.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:373851)]
[2021-08-16 08:46:22.259] [DEBUG] Not an executable: c:\Users\maxim\develop\nx-build\Debug\bin\plugins\ [Error: Not a native executable extension on win32: c:\Users\maxim\develop\nx-build\Debug\bin\plugins\
	at Object.e.isNativeExecutableAsync (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:437987)
	at c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:337692
	at e.ExecutableConfig.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:338544)
	at async Promise.all (index 0)
	at async o.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:346914)
	at async e.SharedVariables._shared.u.SharedVariables.e [as loadWithTask] (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:368776)
	at async m.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:373851)]
[2021-08-16 08:46:22.259] [DEBUG] Not an executable: c:\Users\maxim\develop\nx-build\Debug\bin\plugins_optional\ [Error: Not a native executable extension on win32: c:\Users\maxim\develop\nx-build\Debug\bin\plugins_optional\
	at Object.e.isNativeExecutableAsync (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:437987)
	at c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:337692
	at e.ExecutableConfig.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:338544)
	at async Promise.all (index 0)
	at async o.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:346914)
	at async e.SharedVariables._shared.u.SharedVariables.e [as loadWithTask] (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:368776)
	at async m.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:373851)]
[2021-08-16 08:46:22.259] [DEBUG] Not an executable: c:\Users\maxim\develop\nx-build\Debug\bin\translations\ [Error: Not a native executable extension on win32: c:\Users\maxim\develop\nx-build\Debug\bin\translations\
	at Object.e.isNativeExecutableAsync (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:437987)
	at c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:337692
	at e.ExecutableConfig.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:338544)
	at async Promise.all (index 0)
	at async o.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:346914)
	at async e.SharedVariables._shared.u.SharedVariables.e [as loadWithTask] (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:368776)
	at async m.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:373851)]
[2021-08-16 08:46:22.259] [DEBUG] Not an executable: c:\Users\maxim\develop\nx-build\Debug\bin\vmaxproxy\ [Error: Not a native executable extension on win32: c:\Users\maxim\develop\nx-build\Debug\bin\vmaxproxy\
	at Object.e.isNativeExecutableAsync (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:437987)
	at c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:337692
	at e.ExecutableConfig.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:338544)
	at async Promise.all (index 0)
	at async o.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:346914)
	at async e.SharedVariables._shared.u.SharedVariables.e [as loadWithTask] (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:368776)
	at async m.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:373851)]
[2021-08-16 08:46:22.260] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '${absDirpath}',
  resolved: 'c:\\Users\\maxim\\develop\\nx-build\\Debug\\bin',
  strictAllowed: false
}
[2021-08-16 08:46:22.260] [DEBUG] ExecutableConfig.resolveVariable:  { value: {}, resolved: {}, strictAllowed: true }
[2021-08-16 08:46:23.110] [DEBUG] Not a test executable: c:\Users\maxim\develop\nx-build\Debug\bin\nx_vms_client_desktop_ut.exe reason: [Error: Not a supported test executable: DefaultSpawnerc:\Users\maxim\develop\nx-build\Debug\bin\nx_vms_client_desktop_ut.exe
 stdout: 
 stderr: 
	at c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:353272
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:337767
	at async e.ExecutableConfig.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:338580)
	at async Promise.all (index 0)
	at async o.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:346914)
	at async e.SharedVariables._shared.u.SharedVariables.e [as loadWithTask] (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:368776)
	at async m.load (c:\Users\maxim\.vscode\extensions\matepek.vscode-catch2-test-adapter-3.6.27\out\dist\main.js:2:373851)]
[2021-08-16 08:46:23.111] [INFO] load finished 0

**Comment by matepek** [comment]
Hello,
env variables should work fine. My guess is that your path is mailformed.
Instead of `"PATH": "${os_env:PATH};c:/Path/to/qt/bin"` try `"Path": "${os_env:Path};c:\\Path\\to\\qt\\bin"`.

**Comment by maximMalofeev** [comment]
Thanks a lot. Yes, you right, if do like you suggest it works fine!
