### ISSUE TITLE
Error: Not a supported test executable

### ISSUE THREAD

**Issue by lpanichi** [matepek/vscode-catch2-test-adapter#297]
**Checklist**

- [ yep] The issue is about this extension and NOT about a fork.
- [ done] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [ confirming 3.6.33] The latest version of the extension was used.
- [checked] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**
I have a simple catch2 test :
```
#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch2/catch.hpp"

unsigned int Factorial( unsigned int number ) {
    return number <= 1 ? number : Factorial(number-1)*number;
}

TEST_CASE( "Factorials are computed", "[factorial]" ) {
    REQUIRE( Factorial(1) == 1 );
    REQUIRE( Factorial(2) == 2 );
    REQUIRE( Factorial(3) == 6 );
    REQUIRE( Factorial(10) == 3628800 );
}
```

that is not properly detected by the extension.
I'm not using a remote plugin, ssh or any fancy thing but I'm using vscode in portable mode on windows 10.
I'm also using msys2 in a portable fashion.
The extension ouput when I'm trying to update the tests list is the following

```
[2021-11-22 09:56:39.482] [INFO] load called
[2021-11-22 09:56:39.482] [DEBUG] canceled
[2021-11-22 09:56:39.482] [INFO] `test.advancedExecutables` is not defined. trying to use `test.executables`
[2021-11-22 09:56:39.482] [INFO] load started
[2021-11-22 09:56:39.483] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '${workspaceFolder}/build/tests/*.exe',
  resolved: 'c:\\myspace\\codes\\experiment-catch2/build/tests/*.exe',
  strictAllowed: false
}
[2021-11-22 09:56:39.483] [INFO] pattern ${workspaceFolder}/build/tests/*.exe c:\myspace\codes\experiment-catch2 {
  isAbsolute: true,
  absPath: 'c:\\myspace\\codes\\experiment-catch2\\build\\tests\\*.exe',
  isPartOfWs: true,
  relativeToWsPosix: 'build/tests/*.exe'
}
[2021-11-22 09:56:39.483] [INFO] Absolute path is used for workspace directory. This is unnecessary, but it should work.
[2021-11-22 09:56:39.483] [INFO] fswatcher: using vscode undefined
[2021-11-22 09:56:39.590] [DEBUG] Checking file for tests: c:\myspace\codes\experiment-catch2\build\tests\test_hello.exe
[2021-11-22 09:56:39.590] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '${absDirpath}',
  resolved: 'c:\\myspace\\codes\\experiment-catch2\\build\\tests',
  strictAllowed: false
}
[2021-11-22 09:56:39.590] [DEBUG] ExecutableConfig.resolveVariable:  { value: {}, resolved: {}, strictAllowed: true }
[2021-11-22 09:56:39.639] [DEBUG] Not a test executable: c:\myspace\codes\experiment-catch2\build\tests\test_hello.exe reason: [Error: Not a supported test executable: DefaultSpawnerc:\myspace\codes\experiment-catch2\build\tests\test_hello.exe
 stdout: 
 stderr: 
	at c:\myspace\tools\VSCode-win32-x64-1.62.2\data\extensions\matepek.vscode-catch2-test-adapter-3.6.33\out\dist\main.js:2:355649
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\myspace\tools\VSCode-win32-x64-1.62.2\data\extensions\matepek.vscode-catch2-test-adapter-3.6.33\out\dist\main.js:2:339993
	at async e.ExecutableConfig.load (c:\myspace\tools\VSCode-win32-x64-1.62.2\data\extensions\matepek.vscode-catch2-test-adapter-3.6.33\out\dist\main.js:2:340806)
	at async Promise.all (index 0)
	at async o.load (c:\myspace\tools\VSCode-win32-x64-1.62.2\data\extensions\matepek.vscode-catch2-test-adapter-3.6.33\out\dist\main.js:2:349287)
	at async e.SharedVariables._shared.u.SharedVariables.e [as loadWithTask] (c:\myspace\tools\VSCode-win32-x64-1.62.2\data\extensions\matepek.vscode-catch2-test-adapter-3.6.33\out\dist\main.js:2:371175)
	at async m.load (c:\myspace\tools\VSCode-win32-x64-1.62.2\data\extensions\matepek.vscode-catch2-test-adapter-3.6.33\out\dist\main.js:2:376261)]
[2021-11-22 09:56:39.639] [INFO] load finished 0
```

I tried to run  `.\test_hello.exe "[.],*" --verbosity high --list-tests --use-colour no` with result:

```
Matching test cases:
  Factorials are computed
    C:\myspace\codes\experiment-catch2\tests\test_hello.cpp:8
    (NO DESCRIPTION)
      [factorial]
1 matching test case
```

The solution to the problem was to update the system path with the path to `...\msys64\mingw64\bin`. I may be that this directory contains some libraries needed to run executables on windows. These libraries can not be installed on the system (corporate policy).

The fact is that this path :  `...\msys64\mingw64\bin` is already registered in the `settings.json`:
```
    "terminal.integrated.env.windows": {
        "path": "C:myspace/libs/msys64/mingw64/bin"
    },
```
but somehow was not added to the path used by testMate.
This trick, update the system path, was far from obvious, I really think we got lucky. I believe it could be nice to use the path declared in `settings.json` in this extension.

**Comment by matepek** [comment]
Hello,

Sorry to hear that.
Thinking about that `terminal.integrated.env.windows`...
Tests/executables should not depend on vscode itself, right? I mean if your tests can be run only in vscode that might cause issue in CI, etc.. And that fact that you need that extra path in PATH means that.

Also that config `terminal.integrated.env.windows` was set manually I guess.

Anyhow I added some limited support regarding to this. (in case of change a reload is required)

Will be released in version >= 4.0.2
